"""Create capture table v2

Revision ID: 0aaaca05eca8
Revises: e1feac39f6b7
Create Date: 2023-02-07 16:22:46.235912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaaca05eca8'
down_revision = 'e1feac39f6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('r', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('n', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('b', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('q', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('k', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('P', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('R', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('N', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('B', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('Q', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('K', sa.SmallInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captures')
    # ### end Alembic commands ###
