"""Another attempt to autodetect column type change)

Revision ID: 27ba8f57336d
Revises: 85670409626f
Create Date: 2023-03-01 18:18:08.125481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ba8f57336d'
down_revision = '85670409626f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'winner',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using='winner::integer'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'winner',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True,
                    postgresql_using='winner::varchar')
    # ### end Alembic commands ###
