"""Add column draw to games table

Revision ID: 5e8b58355de6
Revises: 2e583b3737e8
Create Date: 2023-02-28 20:34:25.001531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8b58355de6'
down_revision = '2e583b3737e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('draw', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'draw')
    # ### end Alembic commands ###
