"""Add Tokens table to store refresh tokens

Revision ID: 90497c6c1bbd
Revises: 9f0f83b051ab
Create Date: 2023-02-18 01:15:14.815231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90497c6c1bbd'
down_revision = '9f0f83b051ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
