"""Same as before, since last update was unsuccessful

Revision ID: 9f0f83b051ab
Revises: 9eec98c5fd69
Create Date: 2023-02-16 12:04:38.036314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0f83b051ab'
down_revision = '9eec98c5fd69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('end_reason', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('checked_king', sa.String(), nullable=True))
    op.add_column('games', sa.Column('enpassant_position', sa.ARRAY(sa.Integer()), server_default='{}', nullable=True))
    op.drop_column('games', 'win_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('win_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('games', 'enpassant_position')
    op.drop_column('games', 'checked_king')
    op.drop_column('games', 'end_reason')
    # ### end Alembic commands ###
