"""Add steps column to games table

Revision ID: afecfc63753e
Revises: 27ba8f57336d
Create Date: 2023-03-09 01:37:39.871667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afecfc63753e'
down_revision = '27ba8f57336d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('steps', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'steps')
    # ### end Alembic commands ###
