"""Add Tokens table to store refresh tokens

Revision ID: b33367a46e4e
Revises: 90497c6c1bbd
Create Date: 2023-02-18 01:16:44.238102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33367a46e4e'
down_revision = '90497c6c1bbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
