"""Add relationship to games table

Revision ID: c7c027d443f4
Revises: e155cb7d7996
Create Date: 2023-02-07 21:07:48.624253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c027d443f4'
down_revision = 'e155cb7d7996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
