"""Create Game table

Revision ID: ca67cc5d6c66
Revises: 0aaaca05eca8
Create Date: 2023-02-07 17:03:31.209541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca67cc5d6c66'
down_revision = '0aaaca05eca8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('white_player', sa.Integer(), nullable=False),
    sa.Column('black_player', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(), server_default='rnbqkbnr#pppppppp#8#8#8#8#PPPPPPPP#RNBQKBNR', nullable=False),
    sa.Column('active_player', sa.String(), server_default='w', nullable=False),
    sa.Column('last_move_start', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('last_move_end', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('move_history', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('white_king_pos', sa.ARRAY(sa.Integer()), server_default='{0,4}', nullable=True),
    sa.Column('black_king_pos', sa.ARRAY(sa.Integer()), server_default='{7,4}', nullable=True),
    sa.Column('castle_eligibility', sa.ARRAY(sa.BOOLEAN()), server_default="{TRUE,TRUE,TRUE,TRUE}", nullable=True),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.Column('is_concluded', sa.BOOLEAN(), server_default='FALSE', nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('win_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['black_player'], ['users.id'], ),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['white_player'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
