"""Update column name of games table

Revision ID: e155cb7d7996
Revises: ca67cc5d6c66
Create Date: 2023-02-07 21:02:41.169396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e155cb7d7996'
down_revision = 'ca67cc5d6c66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('white_player_id', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('black_player_id', sa.Integer(), nullable=False))
    op.drop_constraint('games_black_player_fkey', 'games', type_='foreignkey')
    op.drop_constraint('games_white_player_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['white_player_id'], ['id'])
    op.create_foreign_key(None, 'games', 'users', ['black_player_id'], ['id'])
    op.drop_column('games', 'black_player')
    op.drop_column('games', 'white_player')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('white_player', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('black_player', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_white_player_fkey', 'games', 'users', ['white_player'], ['id'])
    op.create_foreign_key('games_black_player_fkey', 'games', 'users', ['black_player'], ['id'])
    op.drop_column('games', 'black_player_id')
    op.drop_column('games', 'white_player_id')
    # ### end Alembic commands ###
