"""Create capture table

Revision ID: e1feac39f6b7
Revises: bb4b4125fab5
Create Date: 2023-02-07 16:17:01.626438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1feac39f6b7'
down_revision = 'bb4b4125fab5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
