"""Change winner column in games table to integer from string

Revision ID: ef6bfa9b391d
Revises: 5e8b58355de6
Create Date: 2023-03-01 18:03:50.658921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6bfa9b391d'
down_revision = '5e8b58355de6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
