"""Add captures relationship to Game table

Revision ID: f6b86df47b1e
Revises: c7c027d443f4
Create Date: 2023-02-08 18:01:12.581441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b86df47b1e'
down_revision = 'c7c027d443f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
